#include <>
#include <>
void main(){
    char s[14]=”md “; int man,i,j,k,l,m,n,o,p,q,r;
    for(man=1;man<=10;man++){
        for(i=65;i<122;i++){
            s[3]=i;
            s[4]=0;
            if(man==1){
                system(s);
                continue;
            }
            for(j=65;j<122;j++){
                s[4]=j;
                s[5]=0;
                if(man==2){
                    system(s);
                    continue;
                }
                for(k=65;k<122;k++){
                    s[5]=k;
                    s[6]=0;
                    if(man==3){
                        system(s);
                        continue;
                    }
                    for(l=65;l<122;l++){
                        s[6]=l;
                        s[7]=0;
                        if(man==4){
                            system(s);
                            continue;
                        }
                        for(m=65;m<122;m++){
                            s[7]=m;
                            s[8]=0;
                            if(man==5){
                                system(s);
                                continue;
                            }
                            for(n=65;n<122;n++){
                                s[8]=n;
                                s[9]=0;
                                if(man==6){
                                    system(s);
                                    continue;
                                }
                                for(o=65;o<122;o++){
                                    s[9]=o;
                                    s[10]=0;
                                    if(man==7){
                                        system(s);
                                        continue;
                                    }
                                    for(p=65;p<122;p++){
                                        s[10]=p;
                                        s[11]=0;
                                        if(man==8){
                                            system(s);
                                            continue;
                                        }
                                        for(q=65;q<122;q++){
                                            s[11]=q;
                                            s[12]=0;
                                            if(man==9){
                                                system(s);
                                                continue;
                                            }
                                            for(r=65;r<122;r++){
                                                s[12]=r;
                                                s[13]=0;
                                                if(man==10){
                                                    system(s);
                                                    continue;
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}